In [1]:
import pandas as pd
import numpy as np

In [2]:
labels = ['a', 'b', 'c']
md = [10, 20, 30]
ar1 = np.array(md)
ar1

array([10, 20, 30])

In [3]:
d = {'a':10, 'b':20, 'c':30}

In [4]:
pd.Series(md)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(md, labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(ar1, labels)

a    10
b    20
c    30
dtype: int32

In [8]:
ser1 = pd.Series([1,2,3,4], ['USA', 'Germany', 'USSR', 'JAPAN'])
ser1

USA        1
Germany    2
USSR       3
JAPAN      4
dtype: int64

In [9]:
ser2 = pd.Series([1,2,5,4],['USA', 'Germany', 'Italy', 'JAPAN'])
ser2

USA        1
Germany    2
Italy      5
JAPAN      4
dtype: int64

In [10]:
ser1['USA']

1

In [11]:
ser3 = ser1 + ser2
ser3

Germany    4.0
Italy      NaN
JAPAN      8.0
USA        2.0
USSR       NaN
dtype: float64

In [12]:
a1 = np.random.randn(10)
a1

array([-1.72916761, -1.85970208, -0.46354973,  0.23347035, -0.19550618,
        0.20600592,  1.78537374, -0.25770854,  0.84943302,  1.18715843])

In [13]:
a2 = np.random.randn(3,3)
a2

array([[ 0.30351876,  1.53532958, -1.38135638],
       [ 0.70146779, -2.70536039, -0.32437208],
       [ 0.11865979,  0.21414099,  0.79252621]])

In [14]:
np.random.seed(101)

In [15]:
from numpy.random import randn

In [16]:
df = pd.DataFrame(randn(5,4), ['A','B','C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])

In [17]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [18]:
df['X']

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [19]:
df['X']['C']

0.7401220570561068

In [20]:
type(df['X'])

pandas.core.series.Series

In [21]:
type(df)

pandas.core.frame.DataFrame

In [22]:
df[['W', 'Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [23]:
df['new']= df['W'] + df['Y']
df['new']

A    3.614819
B   -0.196959
C   -1.489355
D   -0.744542
E    2.796762
Name: new, dtype: float64

In [24]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [25]:
df.drop('new', axis =1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [27]:
df.drop('new', axis = 1, inplace = True)
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [28]:
df.shape

(5, 4)

In [29]:
df.loc['C']

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [30]:
df.iloc[2]


W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [31]:
df.loc['B', 'Y']

-0.8480769834036315

In [32]:
df.loc[['A', 'B'],['W', 'Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [33]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [34]:
booldf = df>0

In [35]:
booldf

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [36]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [38]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [39]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
df[df['Z']<0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [41]:
result = df[df['Z']<0]

In [42]:
result

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [43]:
df[df['W']>0]['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [44]:
df[df['W']>0][['Y', 'X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [45]:
bools = df['W']>0
result = df[bools]
result

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
bools = df['W']>0
result = df[bools]
result[['Y', 'X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [47]:
df[(df['W']>0)  & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [48]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [49]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [50]:
newind = 'CA NY MI WY TX'.split()
newind

['CA', 'NY', 'MI', 'WY', 'TX']

In [51]:
df['states'] = newind
df

W         X         Y         Z states
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     MI
D  0.188695 -0.758872 -0.933237  0.955057     WY
E  0.190794  1.978757  2.605967  0.683509     TX

In [52]:
df.set_index('states')

W         X         Y         Z
states                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
MI     -2.018168  0.740122  0.528813 -0.589001
WY      0.188695 -0.758872 -0.933237  0.955057
TX      0.190794  1.978757  2.605967  0.683509

In [53]:
df

W         X         Y         Z states
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     MI
D  0.188695 -0.758872 -0.933237  0.955057     WY
E  0.190794  1.978757  2.605967  0.683509     TX